# SLEEP STAGE
UNKNOWN = -1
AWAKE = 0
REM = 1
NON_REM = 2

# RHYTHM FREQ
ALPHA_LOW = 8
ALPHA_HIGH = 13
BETA_LOW = 13
BETA_HIGH = 20
THETA_LOW = 4
THETA_HIGH = 8
DELTA_LOW = 0.5
DELTA_HIGH = 4

# DEFAULTS

WINDOW_DEFAULT = 5
EPOCHS_DEFAULT = 5
SAMPLING_FREQ_DEFAULT = 100
MODEL_NAME = 'model_{}'
MODEL_NAME_DEFAULT = 'model_default_name'
DEPRECATED_REASON = 'Old issue solution'

# DICTIONARY_KEYS
SAMPLING_FREQ = 'sampling_freq'

PHYSIONET_DIR = '/home/pc/mgr/physionet'
PHYSIONET_DIR_LOAD = PHYSIONET_DIR + '/{}'

# AI
MODEL_FILE_EXTENSION = '.model'
MODEL_FILE = MODEL_NAME_DEFAULT + MODEL_FILE_EXTENSION

LOG_DATE_TIME_FORMAT = '%Y-%m-%d %H:%M:%S'

# DIRECTORY
MAIN_FEATURE_DIR = '/home/pc/mgr/features'
DATE_FEATURE_DIR = MAIN_FEATURE_DIR + '/{}'
TEST_FEATURE_DIR = DATE_FEATURE_DIR + '/test'
TRAINING_FEATURE_DIR = DATE_FEATURE_DIR + '/training'
# FILE
TEST_FEATURE_FILE_DIR = TEST_FEATURE_DIR + '/{}'
TRAINING_FEATURE_FILE_DIR = TRAINING_FEATURE_DIR + '/{}'
