# SLEEP STAGE
UNKNOWN = -1
AWAKE = 0
REM = 1
NON_REM = 2

# RHYTHM FREQ
ALPHA_LOW = 8
ALPHA_HIGH = 13
BETA_LOW = 13
BETA_HIGH = 20
THETA_LOW = 4
THETA_HIGH = 8
DELTA_LOW = 0.5
DELTA_HIGH = 4

# DEFAULTS

WINDOW_DEFAULT = 5
EPOCHS_DEFAULT = 5
SAMPLING_FREQ_DEFAULT = 200
MODEL_NAME = 'model_{}'
MODEL_NAME_DEFAULT = 'model_default_name'
DEPRECATED_REASON = 'Old issue solution'

# DICTIONARY_KEYS
EXAMINATIONS_KEY = "examinations"
FEATURES_KEY = "features"
WINDOW_WIDTH_KEY = "window_width"
STAGE_MODE_KEY = 'stage_mode'
EPOCHS_KEY = 'epochs'
TRAINING_PART_KEY = 'training_part_percentage'
CLASSIFY_KEY = 'classify'

FEATURES_TITLES_KEY = "titles"
FEATURES_CALLBACKS_KEY = "callbacks"

SAMPLING_FREQ = 'sampling_freq'

# EXCEPTION MESSAGES
WINDOW_SIZE_EXCEPTION_MESSAGE = "Illegal window size exception"

UNIVERSITE_DE_MONS = "/home/pc/mgr/mgr_data/{}.edf"
UNIVERSITE_DE_MONS_HYPNOGRAM_AASM = \
    "/home/pc/mgr/mgr_data/HypnogramAASM_{}.txt"
UNIVERSITE_DE_MONS_HYPNOGRAM_RK = \
    "/home/pc/mgr/mgr_data/HypnogramR&K_{}.txt"

# AI
FEATURE_NAME = "eeg_features"
MODEL_FILE_EXTENSION = '.model'
MODEL_FILE = MODEL_NAME_DEFAULT + MODEL_FILE_EXTENSION

LOG_DATE_TIME_FORMAT = '%Y-%m-%d %H:%M:%S'

# ***********************LOAD_EDF************************
# ECG
LOAD_EDF_ECG_NO = 0

# EEG
LOAD_EDF_EEG_FPI_A2_NO = 1
LOAD_EDF_EEG_CZ_A1_NO = 2
LOAD_EDF_EEG_O1_A2_NO = 15
LOAD_EDF_EEG_FP2_A1_NO = 16
LOAD_EDF_EEG_O2_A1_NO = 17
LOAD_EDF_EEG_CZ2_A1_NO = 18

# EMG
LOAD_EDF_EMG1_NO = 3
LOAD_EDF_EMG2_NO = 19
LOAD_EDF_EMG3_NO = 22

# EOG
LOAD_EDF_EOG1_A2_NO = 4
LOAD_EDF_EOG2_A2_NO = 14

# OTHER
LOAD_EDF_VTH_NO = 5
LOAD_EDF_VAB_NO = 6
LOAD_EDF_NAF2P_A1_NO = 7
LOAD_EDF_NAF1_NO = 8
LOAD_EDF_PHONO_NO = 9
LOAD_EDF_PR_NO = 10
LOAD_EDF_SAO2_NO = 11
LOAD_EDF_PCPAP_NO = 12
LOAD_EDF_POS_NO = 13
LOAD_EDF_PULSE_NO = 20
LOAD_EDF_VTOT_NO = 21

# **********LOAD_FROM_EEG_SIGNAL_ARRAY****************

# EEG
EEG_FPI_A2_NO = 0
EEG_CZ_A1_NO = 1
EEG_O1_A2_NO = 2
EEG_FP2_A1_NO = 3
EEG_O2_A1_NO = 4
EEG_CZ2_A1_NO = 5
EOG1_A2_NO = 6
EOG2_A2_NO = 7
